language: objective-c
osx_image: xcode10.2

env:
  global:
    - PROJECT="SwiftyOpenCC.xcodeproj"
    - SCHEME="SwiftyOpenCC-Package"
  matrix:
    - ACTION=test   PLATFORM=macOS      DESTINATION='platform=OS X'
    - ACTION=test   PLATFORM=iOS        DESTINATION='platform=iOS Simulator,name=iPhone 8'
    - ACTION=test   PLATFORM=tvOS       DESTINATION='platform=tvOS Simulator,name=Apple TV 4K'

before_script:
  - set -o pipefail

script:
  - xcodebuild $ACTION
    -project "$PROJECT"
    -scheme "$SCHEME"
    -destination "$DESTINATION" | xcpretty
